name: QuacktopiaSafety
version: ${project.version}
main: com.quacktopia.quacktopiasafety.QuacktopiaSafety
api-version: 1.13
authors: [ hicupalot ]
description: Keeping Quacktopia Safe
commands:
  nvoff:
    description: Turns off your nightvision
    default: non-op
  quacktest:
    description: Tests if its working
    default: non-op
permissions:
  quacktopia.staff:
    description: Staff Permission
    default: op
